name: 'Autosana CI Upload'
description: 'Upload your built mobile app to Autosana via CI'
inputs:
  api-key:
    description: 'Your Autosana API key'
    required: true
  bundle-id:
    description: 'Your app’s bundle ID'
    required: true
  platform:
    description: 'Platform (e.g., android, ios)'
    required: true
  build-path:
    description: 'Full path to the APK/IPA file (e.g., android/app/build/outputs/apk/release/app-release.apk)'
    required: true
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/entrypoint.sh
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        AUTOSANA_KEY: ${{ inputs.api-key }}
        BUNDLE_ID: ${{ inputs.bundle-id }}
        PLATFORM: ${{ inputs.platform }}
        BUILD_PATH: ${{ inputs.build-path }}