name: Autosana Mobile Testing

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build iOS app
        run: xcodebuild -workspace *.xcworkspace -scheme * -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' build

      - name: Create .app archive
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r app-ios.zip *.app

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/Build/Products/Debug-iphonesimulator/app-ios.zip

  test-autosana:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Notify Autosana
        run: |
          echo "Build artifacts ready for Autosana testing"
          echo "Workflow run ID: ${{ github.run_id }}"
          echo "The Autosana GitHub App will automatically process these artifacts"
